### ISSUE TITLE
Option to search for dev dependencies

### ISSUE THREAD

**Issue by feross** [opbeat/dependency-land#1]
Great work on this project! Love the clean, simple design.

It would be great if there was a way to search for dev dependencies, since packages like `standard` are mostly used as dev dependencies, for example.

**Comment by watson** [comment]
@feross I left out devDependencies because I didn't think it was relevant, but good point with testing modules like standard

**Comment by feross** [comment]
@watson Don't worry about it if it's a lot of work, but it would be interesting to see how much old versions of browserify are used, for instance. Rock on! 👍

**Comment by watson** [comment]
@feross published 😃 @vanjacosic added a checkbox where you can switch the search to only search dev-dependencies. Works with perma-links as well, e.g: standard v7: https://dependency.land/standard/7?dev=1

**Comment by feross** [comment]
Very neat, this is a really easy way to see how many packages depend on `standard`, love it 👍
