### ISSUE TITLE
Shareable links

### ISSUE THREAD

**Issue by feross** [opbeat/dependency-land#2]
After doing a search, it would be great if the URL changed to a permalink that could be shared with friends, or on social media.

**Comment by vanjacosic** [comment]
Thanks for the suggestion, Feross.

I have actually already been working on adding a router and permalinks this week - but ran into some bugs that I am still ironing out.

I'll make sure to let you know once it's working and available!

**Comment by feross** [comment]
@vanjacosic Cool, great work 👍

**Comment by vanjacosic** [comment]
@feross alright, it took a few more days because of ops troubles.. but it works now! 🚀 

Permalink: https://dependency.land/standard/%5E6.5

It also supports scoped packages:

https://dependency.land/%40angular%2Frouter/~3.5

Thanks to @watson for reminding me about those 🙈

**Comment by feross** [comment]
Nice, very cool! Will share it with twitter :)
