### ISSUE TITLE
Search currently not working

### ISSUE THREAD

**Issue by sonicdoe** [opbeat/dependency-land#9]
Because `dependency-db` v3 [now uses a different index](https://github.com/watson/dependency-db/commit/0fcac05af932ad2ca9de4cbd6e1160e74110d2ac) (`!index!dep!` instead of `!index!`), the old cache doesn’t work anymore. This causes search to no longer work on [dependency.land](https://dependency.land).

**Comment by watson** [comment]
@sonicdoe good catch! Thanks 👍 I've fixed it in #10 - It will be shipped as soon as @vanjacosic gets a chance to deploy it 😃

**Comment by vanjacosic** [comment]
@sonicdoe yes, thanks for reporting this. 
I deployed it yesterday thinking that the updater just had to run for a few hours before results would start showing up. 
I just deployed @watson's latest PR and it's back up and running again 🙌
